//@version=6
indicator(title="On Balance Volume & Bolliner Bands", shorttitle="OBV + BB", format=format.volume, timeframe="", timeframe_gaps=true)
var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")
src = close
obv = ta.cum(math.sign(ta.change(src)) * volume)
plot(obv, color=#2962FF, linewidth = 2, title="OnBalanceVolume")

// Smoothing MA inputs
GRP = "Smoothing"
TT_BB = "Only applies when 'SMA + Bollinger Bands' is selected. Determines the distance between the SMA and the bands."
maTypeInput = input.string("SMA + Bollinger Bands", "Type", options = ["None", "SMA", "SMA + Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group = GRP, display = display.data_window)
var isBB = maTypeInput == "SMA + Bollinger Bands"
maLengthInput = input.int(20, "Length", group = GRP, display = display.data_window, active = maTypeInput != "None")
bbMultInput = input.float(2.0, "BB StdDev", minval = 0.001, maxval = 50, step = 0.5, tooltip = TT_BB, group = GRP, display = display.data_window, active = isBB)
var enableMA = maTypeInput != "None"

// Smoothing MA Calculation
ma(source, length, MAtype) =>
	switch MAtype
		"SMA"                   => ta.sma(source, length)
		"SMA + Bollinger Bands" => ta.sma(source, length)
		"EMA"                   => ta.ema(source, length)
		"SMMA (RMA)"            => ta.rma(source, length)
		"WMA"                   => ta.wma(source, length)
		"VWMA"                  => ta.vwma(source, length)

// Smoothing MA plots
smoothingMA = enableMA ? ma(obv, maLengthInput, maTypeInput) : na
smoothingStDev = isBB ? ta.stdev(obv, maLengthInput) * bbMultInput : na
basisPlot = plot(smoothingMA, "OBV-based MA", color=color.rgb(255, 217, 0, 50), display = enableMA ? display.all : display.none, linestyle = plot.linestyle_dashed, editable = enableMA)
bbUpperBand = plot(smoothingMA + smoothingStDev, title = "Upper Bollinger Band", color=color.rgb(255, 82, 82, 30), linestyle = plot.linestyle_dashed, linewidth=1, display = isBB ? display.all : display.none, editable = isBB)
bbLowerBand = plot(smoothingMA - smoothingStDev, title = "Lower Bollinger Band", color=color.rgb(76, 175, 79, 30), linestyle = plot.linestyle_dashed, linewidth=1, display = isBB ? display.all : display.none, editable = isBB)
fill(bbUpperBand, bbLowerBand, color= isBB ? color.new(color.green, 98) : na, title="Bollinger Bands Background Fill", display = isBB ? display.all : display.none, editable = isBB)

// EMA rápida para señales
ema10 = ta.ema(obv, 10)
ema10Plot = plot(ema10, "EMA 10", color=color.new(color.purple, 60), linewidth=2)

// Fill dinámico - Tu señal principal
fill(ema10Plot, basisPlot, color=ema10 > smoothingMA ? color.new(#4caf4f, 85): color.new(#ff5252, 85))